title: Concepts in Humanities Data Analysis
description: ENG 682 | Spring 2019 | University of MIami
url: "http://lindsaythomas.net/eng682s19" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: alexander-heimbuch/millidocs
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
